### ISSUE TITLE
iOS 11 cropped text

### ISSUE THREAD

**Issue by Davarg** [stephsharp/MaterialTextField#12]
Strange behaviour with textfield on iOS 11 beta . Text are cropped and placed three dots at the end of string. It is like that your autolayout is broken on newer version of iOS

**Comment by apascual** [comment]
@Davarg I was experiencing the same issue... I submitted already a PR, but since there has been no update here for the last 2 years, I'd recommend you to use check my fork directly: https://github.com/apascual/MaterialTextField.git

Cheers.

**Comment by stephsharp** [comment]
Hi @Davarg & @apascual, I haven't been able to reproduce this so far. Mind posting a screenshot or code snippet? Thanks!

**Comment by apascual** [comment]
@stephsharp Absolutely, here you go. On the first image, the third MFTextField is being edit, on the second one the edition has ended.

![editing](https://user-images.githubusercontent.com/3491658/30631228-cbafc838-9de3-11e7-9329-4629aac3f044.png)
![after](https://user-images.githubusercontent.com/3491658/30631229-cbd6a0ac-9de3-11e7-80be-163655e8ffa1.png)

**Comment by Davarg** [comment]
@stephsharp  I can always reproduce this issue when using textfield in UITableViewCell
@apascual thank you

**Comment by zerozala** [comment]
Try exploring/experimenting the placeholder first before assigning text.

**Comment by doniekelly** [comment]
I have also reproduced this. Seems to take on the size of the placeholder text if it's added. The fork above fixed it for me. Thanks 

Please accept the PR :)
