### ISSUE TITLE
Got an error 'NSConcreteAttributedString initWithString:: nil value'

### ISSUE THREAD

**Issue by haxtorid** [stephsharp/MaterialTextField#17]
Can someone explain what i did wrong, some of my TextField working with MFTextField but another  just display empty placeholder and i am realy sure i already make it to custome class MFTextField and set placeholder

![screen shot 2018-04-19 at 10 01 48 am](https://user-images.githubusercontent.com/15528254/38969177-1e030804-43b9-11e8-8a90-c9142fd21ddc.png)
![screen shot 2018-04-19 at 10 01 33 am](https://user-images.githubusercontent.com/15528254/38969178-1e95597a-43b9-11e8-9fb1-2cd610434388.png)

and app crash after i tap on another MFTextField without fill it

![screen shot 2018-04-19 at 10 21 04 am](https://user-images.githubusercontent.com/15528254/38969795-323a6f44-43bc-11e8-9049-e2379bd45940.png)

*i am working on cell and some MFTextField are work
*sry for bad english

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'NSConcreteAttributedString initWithString:: nil value'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001117a012b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00000001104c0f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000111815245 +[NSException raise:format:] + 197
	3   Foundation                          0x000000010fedb358 -[NSConcreteAttributedString initWithString:] + 135
	4   Foundation                          0x000000010fee4060 -[NSConcreteAttributedString initWithString:attributes:] + 27
	5   MaterialTextField                   0x000000010c748c16 -[MFTextField attributedString:withColor:] + 358
	6   MaterialTextField                   0x000000010c746748 -[MFTextField setAttributedPlaceholder:] + 168
	7   MaterialTextField                   0x000000010c7482e3 -[MFTextField hidePlaceholderLabelAnimated:] + 211
	8   MaterialTextField                   0x000000010c7472ca -[MFTextField layoutPlaceholderLabelAnimated:] + 202
	9   MaterialTextField                   0x000000010c7471a4 -[MFTextField layoutSubviews] + 148
	10  UIKit                               0x000000010dd21a6d -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1439
	11  QuartzCore                          0x000000010c9db61c -[CALayer layoutSublayers] + 159
	12  QuartzCore                          0x000000010c9df7ad _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	13  QuartzCore                          0x000000010c96686c _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 364
	14  QuartzCore                          0x000000010c993946 _ZN2CA11Transaction6commitEv + 500
	15  QuartzCore                          0x000000010c994694 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 76
	16  CoreFoundation                      0x0000000111742c07 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	17  CoreFoundation                      0x0000000111742b5e __CFRunLoopDoObservers + 430
	18  CoreFoundation                      0x0000000111727124 __CFRunLoopRun + 1572
	19  CoreFoundation                      0x0000000111726889 CFRunLoopRunSpecific + 409
	20  GraphicsServices                    0x0000000114d3e9c6 GSEventRunModal + 62
	21  UIKit                               0x000000010dc505d6 UIApplicationMain + 159
	22  GDC Mobile v2                       0x0000000109088007 main + 55
	23  libdyld.dylib                       0x0000000112fa0d81 start + 1
	24  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by stephsharp** [comment]
Hi @haxtorid, thanks for reporting this crash. I am fairly confident [this change](https://github.com/stephsharp/MaterialTextField/commit/417197fd51ca4b4bba1cbfb8dbb13e8f500402f6) should fix the problem. Please test the fix and let me know if it doesn't resolve the crash.
