### ISSUE TITLE
Error label isn't properly laid out if it already exists when the view is loaded

### ISSUE THREAD

**Issue by sharplet** [stephsharp/MaterialTextField#4]
Here's what the text field looks like if it is loaded with an error already set:

![onviewdidload](https://cloud.githubusercontent.com/assets/147686/11861802/c92f09cc-a4d7-11e5-9ff0-c6907513af69.png)

It fixes itself up after you tap on it:

![aftertapping](https://cloud.githubusercontent.com/assets/147686/11861805/d373bc2a-a4d7-11e5-8296-ea7f29c30fc2.png)

**Comment by stephsharp** [comment]
I've pushed a fix to [develop](https://github.com/stephsharp/MaterialTextField/commits/develop). Please test and confirm it fixes your issue. Thanks :smiley:

**Comment by stephsharp** [comment]
Fixed in [v0.2](https://github.com/stephsharp/MaterialTextField/tree/v0.2)

**Comment by sharplet** [comment]
Looking good :100:

**Comment by TEJ227** [comment]
Hi @stephsharp , can you please add a swift example?
