### ISSUE TITLE
When using Masonry, you can't adapt the height of the internal component.

### ISSUE THREAD

**Issue by HellojingQiu** [stephsharp/MaterialTextField#7]
When I set the height to 30, the content of the component will exceed the limit.
I found that in the "prepareForInterfaceBuilder" method, the ErrorLabel was removed.=.=

**Comment by stephsharp** [comment]
I've created a separate issue for adding the error label to `prepareForInterfaceBuilder`, see #21. Closing this issue because it's very old, but if you have further problems with Masonry please open a new issue and provide some sample code if possible. Thanks.
